# Generated by Django 5.2.16 on 2026-08-08 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="user_id",
            new_name="user",
        ),
    ]
