# Generated by Django 5.2.16 on 2026-09-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_last_login"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="address",
            table="addresses",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
