# Generated by Django 5.2.16 on 2026-09-10 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_address_created_at_alter_address_updated_at_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE `users`
                MODIFY `updated_at` DATETIME(6)
                NOT NULL
                DEFAULT CURRENT_TIMESTAMP(6)
                ON UPDATE CURRENT_TIMESTAMP(6);
        """,
            reverse_sql="""
                ALTER TABLE `users`
                MODIFY `updated_at` DATETIME(6)
                NOT NULL
                DEFAULT CURRENT_TIMESTAMP(6);
        """
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE `addresses`
                MODIFY `updated_at` DATETIME(6)
                NOT NULL
                DEFAULT CURRENT_TIMESTAMP(6)
                ON UPDATE CURRENT_TIMESTAMP(6);
         """,
            reverse_sql="""
                ALTER TABLE `addresses`
                MODIFY `updated_at` DATETIME(6)
                NOT NULL
                DEFAULT CURRENT_TIMESTAMP(6);
         """
        )
    ]
