# Generated by Django 5.2.16 on 2026-08-10 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("t_shirts", "T-Shirts"),
                            ("shirts", "Shirts"),
                            ("hoodies", "Hoodies"),
                            ("sweatshirts", "Sweatshirts"),
                            ("sweaters", "Sweaters"),
                            ("jackets", "Jackets"),
                            ("coats", "Coats"),
                            ("jeans", "Jeans"),
                            ("trousers", "Trousers"),
                            ("shorts", "Shorts"),
                            ("dresses", "Dresses"),
                            ("skirts", "Skirts"),
                            ("activewear", "Activewear"),
                            ("underwear", "Underwear"),
                            ("swimwear", "Swimwear"),
                            ("shoes", "Shoes"),
                            ("accessories", "Accessories"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                            ("XXXL", "XXXL"),
                            ("XXXXL", "XXXXL"),
                        ],
                        max_length=15,
                    ),
                ),
                ("price", models.FloatField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("yellow", "Yellow"),
                            ("white", "White"),
                            ("black", "Black"),
                            ("gray", "Gray"),
                            ("brown", "Brown"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                            ("pink", "Pink"),
                            ("beige", "Beige"),
                            ("navy", "Navy"),
                            ("olive", "Olive"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categories",
                    ),
                ),
            ],
        ),
    ]
