# Generated by Django 5.2.16 on 2026-08-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
